### ISSUE TITLE
Can we use only os_mempool without nimBLE

### ISSUE THREAD

**Issue by mantriyogesh** [apache/mynewt-nimble#1212]
The os_mempool code looks promising and wanted to re-use in different project.
But because of dependencies, I have to include complete nimBLE code.

Is there a way to use only mempool module without including complete nimBLE software?

**Comment by andrzej-kaczmarek** [comment]
os_mempool does not depend on NimBLE, it's part of Mynewt: https://github.com/apache/mynewt-core/blob/master/kernel/os/src/os_mempool.c
the copy in the NimBLE repository is only to make porting possible without Mynewt itself.

**Comment by mantriyogesh** [comment]
Thank you for the quick response.
In that case, I will copy selective files which are needed.
