### ISSUE TITLE
Nimble supports AutoPTS based on PTS 8.2.2

### ISSUE THREAD

**Issue by sjanc** [apache/mynewt-nimble#1239]
- [x] - test plan update
- [x] - workspace update
- [x] - GAP
- [x] - GATT
- [x] - SM
- [x] - L2CAP
- [x] - Mesh

**Comment by KKopyscinski** [comment]
ICS were updated here: https://github.com/intel/auto-pts/pull/719 and still are valid
Workspace update: https://github.com/intel/auto-pts/pull/738

**Comment by KKopyscinski** [comment]
@sjanc GAP/SEC/AUT/BV-21-C theoretically passes, but let's not rely on PTS bugs and send event to inform Upper Tester about bond loss https://github.com/apache/mynewt-nimble/pull/1091 :)
