### ISSUE TITLE
bt_mesh_init等函数参数指针判空问题

### ISSUE THREAD

**Issue by mtm509** [apache/mynewt-nimble#1277]
bt_mesh_init等好多向用户提供的接口，指针参数好多都没有判空

**Comment by mtm509** [comment]
bt_mesh_init 等众多向用户提供的接口，指针参数都没有判空
比如还有cfg_cli.h中很多接口，也没有对指针参数判空

**Comment by sjanc** [comment]
Hello,

This forum is international so please use English
