### ISSUE TITLE
LOG_LEVEL defines collision

### ISSUE THREAD

**Issue by vovagorodok** [apache/mynewt-nimble#1416]
At `log_common.h` we have defined:
```
#define LOG_LEVEL_DEBUG    (0)
#define LOG_LEVEL_INFO     (1)
#define LOG_LEVEL_WARN     (2)
#define LOG_LEVEL_ERROR    (3)
#define LOG_LEVEL_CRITICAL (4)
#define LOG_LEVEL_NONE     (5)
```
`LOG_LEVEL..` names are very common and I have redefinition issues when another than NibBle logger is used.\
Because its internal NibBle logger, proposed to use some internal names like:
`BLE_LOG_LEVEL..` or `NIM_BLE_LOG_LEVEL..`

**Comment by vovagorodok** [comment]
What do You think?

**Comment by sjanc** [comment]
Hi,

Currently logs implementation is from  Mynewt but we will extend NPL with logs so that this is no longer the case.
I'm bit busy at the moment but will try to find some time in upcoming weeks to work on this.
Ping me if this is not done i next few weeks :)

**Comment by vovagorodok** [comment]
Ping :)

**Comment by vovagorodok** [comment]
@sjanc found time to rename it?

**Comment by vovagorodok** [comment]
@sjanc I'm back with this topic

**Comment by sjanc** [comment]
should be fixed upstream, sorry it took a bit longer than expected

**Comment by vovagorodok** [comment]
Nice :) Thanks
