### ISSUE TITLE
Where can I find the documentation for nimble-1.4.0 and nimble-1.3.0?

### ISSUE THREAD

**Issue by simple12360** [apache/mynewt-nimble#1538]
It seems like the [Mynewt nimble code](https://github.com/apache/mynewt-nimble/tree/nimble_1_4_0_tag/nimble/host/include/host) (from version 1.1 to 1,5) and [Mynewt BLE User Guide](https://mynewt.apache.org/latest/network/index.html) (from v1.1 to v1.0) follow the different versioning system. If I am developing on nimble v1.3 or 1.4, where can I find the exact documentation for these two versions? I am talking about the documentation hosted [here](https://mynewt.apache.org/latest/network/index.html), not the .rst docs hosted on GitHub, because it does not have the generated API docs.

**Comment by sjanc** [comment]
Hi,

NimBLE is considered internal project of Mynewt and thus we don't provide explicit documentation for nimble versions.
So documentation is always for Mynewt (including BLE features).

I don't think we have explicit mapping for Mynewt<-> NimBLE version used anywhere in documentation but repository.yml [1] should allow for this.  eg  Mynewt 1.9.0 uses nimble 1.4.0

[1]  https://github.com/apache/mynewt-core/blob/master/repository.yml#L107
