### ISSUE TITLE
Where can I find documentation for known vulnerabilities

### ISSUE THREAD

**Issue by RayCxggg** [apache/mynewt-nimble#1609]
Hi, 

I'm working on a Bluetooth firewall project. Since NimBLE is a valuable well-known open-source BLE stack, I'm looking forward to testing the defense ability of the firewall by reproducing known attacks. I wonder whether there is a documentation for known vulnerabilities of NimBLE like the way ZephyrOS provides [here](https://docs.zephyrproject.org/latest/security/vulnerabilities.html).

Thank you.

**Comment by sjanc** [comment]
Hi,

We updated webpage recently and those should be available here:  https://mynewt.apache.org/cve
