### ISSUE TITLE
bletiny application source is missing apps/ repo.

### ISSUE THREAD

**Issue by gladborn** [apache/mynewt-nimble#191]

**Comment by andrzej-kaczmarek** [comment]
`bletiny` was deprecated some time ago and recently removed from repository - use `btshell` instead which supports all the features available in NimBLE

**Comment by gladborn** [comment]
How to compile btshell ? I can't find any Makefile.

**Comment by andrzej-kaczmarek** [comment]
the same way as any other app for Mynewt - you need to create target and build it using `newt` tool
if you did not use Mynewt before, start here: http://mynewt.apache.org/latest/

**Comment by gladborn** [comment]
Do you have any test application for Linux to test ported example code of linux ?

mynewt-nimble-master\porting\examples\linux

**Comment by andrzej-kaczmarek** [comment]
on Linux you can use BlueZ - there are tools like `bluetoothctl` there or just use UI

**Comment by gladborn** [comment]
Thanks. Helpful
