### ISSUE TITLE
Code Size Optimization 

### ISSUE THREAD

**Issue by mfarag13** [apache/mynewt-nimble#224]
Currently we don't have code guards for most of the features that is configured through  syscfg.h
so the code size will be considered large by having features disabled and its code is still exist.
Example:-
if we configure the host to work as a broadcaster only, There will be no connection. But all handling of connections will be available in ble_gap.c and ble_hs_hci_ev.c through dispatch tables. this will increase the image size unnecessarily with unused code.

**Comment by sjanc** [comment]
this is now handled for both host and controller,  ie code for disabled roles and features is not built.
