### ISSUE TITLE
IPv6 support over Bluetooth

### ISSUE THREAD

**Issue by sterlinghughes** [apache/mynewt-nimble#25]
Both over 4.2 as well as directly over extended advertising framework.

**Comment by Citrullin** [comment]
I am not that deep into this topic, but I would say, that's nothing which should be part of this library. You should consider using [myNewt](https://mynewt.apache.org/) or [RIOT OS](https://www.riot-os.org/) for this. Both are using this library. So you are able to use the 6Lowpan stack over bluetooth with it.

**Comment by haukepetersen** [comment]
Just saw this issue again: preliminary IPv6-over-BLE support using NimBLE was merged into RIOT master now.

I think IPv6 over extended advertising framework is not even drafted by standardization bodies, right?!

**Comment by Citrullin** [comment]
@haukepetersen I can confirm this. Already using it with the newest linux kernel. So, this issue not present anymore. Works with Bluetooth >= 4.0.

**Comment by KKopyscinski** [comment]
I'm closing this, NimBLE Bluetooth stack can be used over 6LoWPAN implemented in OS that it's used on
