### ISSUE TITLE
L2CAP: Analyze and fix failing testcases when using AutoPTS 

### ISSUE THREAD

**Issue by michal-narajowski** [apache/mynewt-nimble#265]
This is a general issue that groups all issues with L2CAP testcases when using AutoPTS. AutoPTS for Nimble is still work in process.

Test Case | Result |  
-- | -- | --
L2CAP/LE/CPU/BV-01-C | BTP TIMEOUT | Verify that the IUT is able to send the connection parameter update Request to tester when acting as a slave device.
L2CAP/LE/CPU/BI-01-C | PTS TIMEOUT | Verify that the IUT is able to reject a request for connection parameter update with illegal parameters.

**Comment by michal-narajowski** [comment]
Update 07.01.2019

Test Case | Result |  
-- | -- | --
L2CAP/LE/CPU/BV-01-C | BTP TIMEOUT | Verify that the IUT is able to send the connection parameter update Request to tester when acting as a slave device.

**Comment by michal-narajowski** [comment]
Update 07.02.2019:

Test Case | Result |  
-- | -- | --
L2CAP/COS/CFC/BV-03-C | INCONC | Verify that the IUT can correctly reassemble data received from the Lower Tester which is greater than the IUT LE-frame size.
L2CAP/COS/CFC/BV-04-C | INCONC | Verify that the IUT can receive unsegmented data correctly.

**Comment by michal-narajowski** [comment]
Update 12.02.2019:

All tests pass

**Comment by rymanluk** [comment]
We can close it then
