### ISSUE TITLE
SM: Analyze and fix failing testcases when using AutoPTS

### ISSUE THREAD

**Issue by michal-narajowski** [apache/mynewt-nimble#266]
This is a general issue that groups all issues with SM testcases when using AutoPTS. AutoPTS for Nimble is still work in process.

Test Case | Result |  
-- | -- | --
SM/SLA/KDU/BV-07-C | FAIL | Verify that the IUT correctly handles a requested encrypted session setup to use the distributed LTK, EDIV and Rand values when the key distribution phase has completed
SM/SLA/PKE/BV-05-C | FAIL | Verify that the IUT that supports the Passkey Entry pairing procedure as responder correctly handles an initiator with insufficient security to result in an Authenticated key
SM/SLA/SIE/BV-01-C | FAIL | Verify that the IUT is able to initiate encryption as a slave
SM/SLA/SIP/BV-01-C | FAIL | Verify that the IUT is able to initiate a pairing as a slave

**Comment by michal-narajowski** [comment]
Update 07.01.2019:

Test Case | Result |  
-- | -- | --
SM/SLA/KDU/BV-07-C | FAIL | Verify that the IUT correctly handles a requested encrypted session setup to use the distributed LTK, EDIV and Rand values when the key distribution phase has completed

**Comment by michal-narajowski** [comment]
Update 07.02.2019:

Test Case | Result |  
-- | -- | --
SM/MAS/JW/BV-05-C | PTS TIMEOUT | Verify that the IUT handles Just Works pairing failures
SM/SLA/KDU/BV-02-C | PTS TIMEOUT | Verify that the IUT sends IRK after a successful pairing
SM/SLA/KDU/BV-07-C | FAIL | Verify that the IUT correctly handles a requested encrypted session setup to use the distributed LTK, EDIV and Rand values when the key distribution phase has completed

**Comment by michal-narajowski** [comment]
Update 12.02.2019:

Test Case | Result |  
-- | -- | --
SM/SLA/KDU/BV-07-C | FAIL | Verify that the IUT correctly handles a requested encrypted session setup to use the distributed LTK, EDIV and Rand values when the key distribution phase has completed

**Comment by rymanluk** [comment]
Is it still valid?

**Comment by michal-narajowski** [comment]
This is an old issue, nowadays we have rare failures so we can keep an issue per failed test.
