### ISSUE TITLE
[Ext adv] Add support for periodic advertising

### ISSUE THREAD

**Issue by rymanluk** [apache/mynewt-nimble#268]
This task is split to few subtasks:
<s>
- LL implementation for advertising   -   https://github.com/apache/mynewt-nimble/pull/354
- LL implementation for scanner - https://github.com/apache/mynewt-nimble/pull/440
- Host implementation  -   https://github.com/apache/mynewt-nimble/pull/283 https://github.com/apache/mynewt-nimble/pull/461
- btshell support - https://github.com/apache/mynewt-nimble/pull/461 
- Sync Transfer (5.1 feature) - https://github.com/apache/mynewt-nimble/pull/651
</s>

**Comment by sjanc** [comment]
This task is split to few subtasks:
- LL implementation for advertising   -   https://github.com/apache/mynewt-nimble/pull/354
- LL implementation for scanner
- Host implementation  -   https://github.com/apache/mynewt-nimble/pull/283
