### ISSUE TITLE
nimble: Sometimes we could not connect to a peer device that was using directed advertising

### ISSUE THREAD

**Issue by michal-narajowski** [apache/mynewt-nimble#516]

**Comment by rymanluk** [comment]
@michal-narajowski  is it still valid?

**Comment by prasad-alatkar** [comment]
I am facing similar issue, but in my case if gatt client is not NimBLE based(e.g. bluedroid), can not discover the gatt server using directed advertisement (NimBLE). However when both the devices are NimBLE, I did not face any issue.
