### ISSUE TITLE
hkdf

### ISSUE THREAD

**Issue by Huihh** [apache/mynewt-nimble#561]
Author: 
    I have a question, I used /ext/tinycrypt/* folder code in your project, How could I implement hkdf procedure used your algorithm source code, Please tell me what should I do, Thank you very mush

**Comment by utzig** [comment]
`tinycrypt` already provides an `hmac` construction and API. Sample source for implementing an HKDF from those is given in the RFC: https://tools.ietf.org/html/rfc6234#section-8.4

**Comment by Huihh** [comment]
Thank you very mush, I have Done
