### ISSUE TITLE
Slack invite is not working anymore

### ISSUE THREAD

**Issue by copercini** [apache/mynewt-nimble#600]
The Slack invite link of main readme is broken https://mynewt.slack.com/join/shared_invite/MTkwMTg1ODM1NTg5LTE0OTYxNzQ4NzQtZTU1YmNhYjhkMg 

Is there any other way to join?

**Comment by utzig** [comment]
@copercini https://mynewt.slack.com/join/shared_invite/enQtNjA1MTg0NzgyNzg3LTcyMmZiOGQzOGMxM2U4ODFmMTIwNjNmYTE5Y2UwYjQwZWIxNTE0MTUzY2JmMTEzOWFjYWZkNGM0YmM4MzAxNWQ

**Comment by copercini** [comment]
@utzig Obrigado!
