### ISSUE TITLE
Assert in `ble_ll_scan_start`

### ISSUE THREAD

**Issue by simonratner** [apache/mynewt-nimble#656]
Seeing an assert trigger under load in `ble_ll_scan_start`, line 1010:
```
BLE_LL_ASSERT(scansm->scan_rsp_pending == 0);
```
![image](https://user-images.githubusercontent.com/667283/68991663-e35bc880-0815-11ea-8ddb-7892798873b5.png)

We are initiating the scan proc periodically, with duration of 1500ms, then restarting it once it completes.

Any help appreciated. cc: @lance-proxy.

**Comment by simonratner** [comment]
Running commit 19d7ebf.

**Comment by sjanc** [comment]
Hmm we've been seeing this assert on UPF and hoped that it was fixed but apparently I've missed clearing that also on duration timer fire,  could you try this?
https://github.com/apache/mynewt-nimble/pull/657

**Comment by lance-proxy** [comment]
@sjanc, thanks for your patch. Im working with @simonratner on this. We have updated some of our test devices and have yet to see this assertion yet. I will post here straight away if I observe this assertion.

**Comment by sjanc** [comment]
any update on this? should we keep this stil open for now?

**Comment by lance-proxy** [comment]
Hi @sjanc sorry about the late reply. We have not been hitting this assertion in `ble_ll_scan_start` since adding your patch. I see #657 is merged so I think we can close this issue.
