### ISSUE TITLE
mesh: If the Proxy feature is disabled, a GATT Client device should be able to connect over GATT for configuration and control

### ISSUE THREAD

**Issue by michal-narajowski** [apache/mynewt-nimble#666]
Mesh Profile Specification 1.0.1.
Section 4.2.11  GATT Proxy:
Note: If the Proxy feature is disabled, a GATT client device can connect over GATT to that node for
configuration and control. Messages from the GATT bearer are not relayed to the advertising
bearer.

**Comment by sjanc** [comment]
stil valid?

**Comment by michal-narajowski** [comment]
Solved by this PR: https://github.com/apache/mynewt-nimble/pull/724
