### ISSUE TITLE
Consistent setting of ISR on Nordic chipset

### ISSUE THREAD

**Issue by edoput** [apache/mynewt-nimble#673]
Hello nimble developers,

I'm trying to use nimBLE as a library while my application runs as a FreeRTOS task.

I'm having trouble going through the FreeRTOS porting layer as there are [3 symbols declared](https://github.com/apache/mynewt-nimble/blob/5bdae413d47daa8535f4908c3f7e75e88db563fe/porting/npl/freertos/include/nimble/npl_freertos.h#L68)
that are not implemented in the port.

1. `npl_freertos_hw_set_isr`
2. `npl_freertos_hw_enter_critical`
3. `npl_freertos_hw_exit_critical`

The first symbol is the one that is actually interesting as the other two are never referenced
in the implementation of the [FreeRTOS port](https://github.com/apache/mynewt-nimble/blob/5bdae413d47daa8535f4908c3f7e75e88db563fe/porting/npl/freertos/include/nimble/nimble_npl_os.h#L281).

I'm going though where `ble_npl_hw_set_isr` is used, e.g [ble_hw.c](https://github.com/apache/mynewt-nimble/blob/9c6f8b1ac9208f98df485334e98e85ed0dcd00f1/nimble/drivers/nrf51/src/ble_hw.c#L328), and I see some difference in how the different RTOS want things set up.

The function `ble_npl_hw_set_isr` is still implemented only in the RIOT port so I'm guessing
that MYNEWT exports it in another library.

Moreover the function `ble_npl_hw_set_isr` is not available if [we don't use the nimble controller](https://github.com/apache/mynewt-nimble/blob/92ab01ca9b771777f4249cfbac2aa8801fdcdf4e/nimble/include/nimble/nimble_npl.h#L158) (so we are definitely targeting the nrf5x series chipset)
and I'm thinking that there should be no reason for having this function around as we can rely on the NVIC library for setting interrupts.

Is there a reason the FreeRTOS port is missing an implementation? Is this documented somewhere in the docs?

**Comment by sjanc** [comment]
freertos port should be working OK (there are project like InfiniTime that use NimBLE on Freertos)

You may also look at example here (which was not merged due to licensing issues at that time) https://github.com/apache/mynewt-nimble/pull/81
