### ISSUE TITLE
ble_phy_isr in nrf52 series 

### ISSUE THREAD

**Issue by JaydenH215** [apache/mynewt-nimble#685]
Hi, guys
   How should I understand the following operation, i think there is no correspondence between irq and NRF_RADIO-> SHORTS after i read spec about nrf52832.

    /* Ensures IRQ is cleared */
    irq_en = NRF_RADIO->SHORTS;

Thanks.

**Comment by wes3** [comment]
It is not the greatest comment in the world to be sure, but this comes from the following section in the spec: nrf52832_PS v1.4. Section 15.8.1 Interrupt clearing.

Important: To avoid an interrupt reoccurring before a new event has come, the program should perform a read from one of the peripheral registers, for example, the event register that has been cleared, or the INTENCLR register that has been used to disable the interrupt.

**Comment by JaydenH215** [comment]
Thanks, i got it.
