### ISSUE TITLE
Is there any help document about running on Nrf52840?

### ISSUE THREAD

**Issue by ermaerma** [apache/mynewt-nimble#699]
I have a Nrf52840 hardware. How can i start to compile a Ble5 Peripheral or Central application and run on my Nrf52840? Is there any help document about get started?
 
Thanks.

**Comment by JaydenH215** [comment]
jaydenh215.github.io

我写了一些关于52832的博客，有详细移植到rt-thread的过程，可以参考一下。

**Comment by sjanc** [comment]
you select nrf52840 bsp (nordic_pca10056) in your target as for any other bsp

refer to https://mynewt.apache.org/latest/tutorials/ble/ble_bare_bones.html
