### ISSUE TITLE
Can I run nimble stack on nRF52840DK without RTOS?

### ISSUE THREAD

**Issue by loccs-cp** [apache/mynewt-nimble#723]
Hi~

I'm trying to measure the power consumption of the nRF52840 chip , which runs the nimble full stack.
However, the mynewt RTOS seems to bring too much noise and deeply effect the measurement.
 I want to use nimble without RTOS so that I can get pure measurement results，is it possible? Any suggestions?

Thanks.

**Comment by sjanc** [comment]
no, NimBLE is not supporting bare metal.

but I'm not getting what noise you mean,  when idle idle task should go to sleep until next event is expected
