### ISSUE TITLE
HCI BCSP protocol support

### ISSUE THREAD

**Issue by dmastain** [apache/mynewt-nimble#749]
I'm wondering if there is any plan to support the BCSP HCI over UART standard. I'm in a situation where I would like to use a UART to send HCI commands from Host to Controller but don't have enough pins available for hardware flow control and BCSP seems like a promising solution but it doesn't appear to be currently available in the stack.

Are there currently any other solutions around flow control?

**Comment by rymanluk** [comment]
As far as I know BCSP is (BlueCore Serial Protocol) and since it is not Bluetooth SIG, we don't have motivation for that. However, if somebody I believe will implement it we will accept patches :)

**Comment by LuoZhongYao** [comment]
H5 is the standard protocol of Bluetooth SIG, he is very similar to BCSP, but H5 is simpler
