### ISSUE TITLE
When using NRF52840, the advertising signal is very poor

### ISSUE THREAD

**Issue by yyipk** [apache/mynewt-nimble#767]
When using NRF52840 hardware, the advertising signal is very poor. Even if the TX power is set to the maximum (8dbm), when using NRF52810, the signal is normal. Why is this?

**Comment by yyipk** [comment]
First, the hardware problem of NRF52840 has been eliminated. When using Nordic's Bluetooth stack, the signal of NRF52840 is normal.

**Comment by rymanluk** [comment]
@yyipk  do you still have this issue?
What are the difference you are seeing?

**Comment by sjanc** [comment]
if this is stil valid please reopen
