### ISSUE TITLE
Should 40s timeout apply to connection parameter updates?

### ISSUE THREAD

**Issue by zacwbond** [apache/mynewt-nimble#780]
I have a connection using a connection interval of 120, latency of 90, and timeout of 3000.  The spec says in section 6.B.5.4, 

>The master should allow a minimum of 6 connection events that the slave will be listening for before the instant occurs, considering that the slave may only be listening once every connSlaveLatency events.

Since a connection update isn't done until the new parameters are applied, that means in my case a parameter update will take 120 *1.25ms * 90 * 6 = 81000ms, or 1:21.  

But in `ble_gap.c` there's a hard-coded timeout of `BLE_GAP_UPDATE_TIMEOUT_MS` = 40s applied to connection parameter update events.  I assume 40s was chosen because of 6.B.5.2, but that section also says there's no timeout rules for connection update procedures.  

The result is that in my application, when the peripheral asks for new connection parameters, the master times out and disconnects the peripheral before the process is expected to have completed.

I think the timeout for connection parameter update events should be based on the current connection parameters rather than a hardcoded value.

**Comment by rymanluk** [comment]
Fixed with https://github.com/apache/mynewt-nimble/pull/782
