### ISSUE TITLE
Possible NULL dereference in porting/nimble/src/os_mempool.c

### ISSUE THREAD

**Issue by tluio** [apache/mynewt-nimble#858]
On line 81, the pointer **membuf** is checked in 
  if (membuf != NULL)
This indicates that **membuf** can be NULL.
If so, a NULL dereference bug will occur on line 114:
  SLIST_NEXT(block_ptr, mb_next)

**Comment by sjanc** [comment]
if membuf is NULL, blocks must be 0 (otherwise function returns in line 81) so that while() never loops and thus SLIST_NEXT(block_ptr, mb_next) is not called

**Comment by tluio** [comment]
Sorry, but I wonder if our code is the same? If **blocks** is 0, SLIST_NEXT(block_ptr, mb_next) is also called in line 114.

**Comment by sjanc** [comment]
Looks like this was already fixed in core but nimble copy wasn't updated. We should probably sync copy with core

**Comment by KKopyscinski** [comment]
Fixed in merged patch
