### ISSUE TITLE
Porting to Linux Issue

### ISSUE THREAD

**Issue by bilal7676** [apache/mynewt-nimble#882]
I am trying to execute an example of Linux on my system. But I am getting an error of 

"bind() failed 16 hci0
nimble-linux: ../../../nimble/transport/socket/src/ble_hci_socket.c:880: ble_hci_sock_init: Assertion `Failure configuring socket HCI' failed.
Aborted"

Can you please tell me where am doing wrong?

**Comment by sjanc** [comment]
Hi,

Things to check:
 - run as root (or sudo)
 - make sure hci device is down before running nimble port (bluetoothctl -> power off)

**Comment by KKopyscinski** [comment]
Because of no further replies I'm assuming it's working by now, feel free to reopen if issue persists @bilal7676
