### ISSUE TITLE
ble_hs_cfg: .sm_our_key_dist and .sm_their_key_dist, what are they for?

### ISSUE THREAD

**Issue by lenzarda** [apache/mynewt-nimble#891]
ble_hs_cfg: .sm_our_key_dist and .sm_their_key_dist, what are they for?

**Comment by sjanc** [comment]
those defines allow our and peer keys during pairing key distribution phase
Set Local Keys Distribution, this is a bit field of possible values: LTK (0x01), IRK (0x02), CSRK (0x04), LTK_SC(0x08)

(note that CSRK is not supported in NimBLE)

consult Bluetooth Core specification for details.
