### ISSUE TITLE
ble_hs_cfg: .sm_oob_data_flag, is there an example of a client in linux or windows able to use it?

### ISSUE THREAD

**Issue by lenzarda** [apache/mynewt-nimble#892]
ble_hs_cfg: .sm_oob_data_flag, is there an example of a client in linux or windows able to use it?

If I set the sm_oob_data_flag=1 in https://github.com/apache/mynewt-nimble/tree/master/apps/bleprph which software in Linux or Windows can I use to test it?

**Comment by sjanc** [comment]
You may test this with PTS where you provided OOB data manually (or with autopts setup). 
On linux you may try to experiment with btmgmt local-oob and remote-oob commands (but I haven't use this for a while so don't know state of it)

How to setup OOB pairing on other OSes should be asked on those OSes support forums.
