### ISSUE TITLE
No "Class of Device" (CoD) setter, getter found in API?

### ISSUE THREAD

**Issue by codewitch-honey-crisis** [apache/mynewt-nimble#909]
I need to set the CoD so I can determine if the devices I'm finding are the specific devices I created.

Class of Device is how you do this, no?

bluedroid has this
BluetoothClass
and it exposes that facility.

There is no equivalent here from the looks of things, either for setting it (server) or getting it (client)

I'm looking for a different lightweight library. What would you have me do, connect by name and manufacturer? I am uncomfortable with this without checking the device class.

Or maybe it is here, and the documentation doesn't make it clear.

Either way, it's a problem.

Best regards

**Comment by andrzej-kaczmarek** [comment]
There's no CoD in BLE, it's only used in Bluetooth classic which NimBLE does not support.
If you want to filter devices during discovery you can use either Appearance value or Services UUIDs, both can be present in advertising data.

**Comment by codewitch-honey-crisis** [comment]
I'm sorry. I'm still new to this, and I thought CoD was how you did it.
Thanks!
