### ISSUE TITLE
NimBLE mesh on ESP32 ( Provisioning and configuration data Persistance storage issuse)

### ISSUE THREAD

**Issue by bilalmalik76** [apache/mynewt-nimble#951]
I am using NimBLE mesh on ESP32. But Provisioning and configuration data is not being stored on Persistance storage. I have enabled BLE_MESH_SETTINGS. But there is no config.h file. 

I am getting an error of config.h file not found.

I am using example available in this folder:
`esp-idf/examples/bluetooth/nimble/blemesh/
`
I have enabled the BLE_MESH_SETTINGS from C:\esp\esp-idf\components\bt\host\nimble\port\include\esp_nimble_cfg by making this change:
`#ifndef MYNEWT_VAL_BLE_MESH_SETTINGS #define MYNEWT_VAL_BLE_MESH_SETTINGS (1) #endif
`When I build the project after enabling _BLE_MESH_SETTINGS, I am getting this build error:
In file included from C:/Users/Lenovo/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/mesh/src/glue.c:20: C:/Users/Lenovo/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/mesh/include/mesh/glue.h:56:10: fatal error: config/config.h: No such file or directory #include "config/config.h" ^~~~~~~~~~~~~~~~~ compilation terminated.

**Comment by KKopyscinski** [comment]
Saving provisioning data in persistent storage was recently fixed, does this issue still persist?

**Comment by KKopyscinski** [comment]
As far as I understand, ESP-IDF has NimBLE stack ported for ESP32 and FreeRTOS, so it should be enabled there. Because it's not really NimBLE issue, I'm closing this.
