### ISSUE TITLE
Wiki is blank, but enabled

### ISSUE THREAD

**Issue by fredster33** [apache/mynewt-nimble#961]
The wiki is currently blank, but enabled in repository settings. This causes the "Wiki" tab to appear, but when users click on the "WIki" tab, it redirects to the project page, causing potential confusion. The "Wiki" function on this repository should be disabled.

**Comment by sjanc** [comment]
I've added link to wiki on apache.org

**Comment by fredster33** [comment]
All right, closing this as resolved.
