### ISSUE TITLE
Suggest change the name of function `ble_gattc_notify` and `ble_gattc_notify_custom` into `ble_gatts_notify`and `ble_gatts_notify_custom`

### ISSUE THREAD

**Issue by Wth-Esp** [apache/mynewt-nimble#983]
Notify procedure can only be operated by GATT Server.

So, I think the ble_gattc_notify is not a proper name for notify, it makes me confuse when I call this function to customize a notify from server to client.

**Comment by sjanc** [comment]
yes, this is currently for historical reasons :)  but I'm totally fine with adding wrappers with fixed names and marking old ones as deprecated.  Would you like to send such PR?

**Comment by Wth-Esp** [comment]
@sjanc Yes, I'm willing to do this. Please wait for my updates, maybe I will change other mistakes by the way. When the PR is ready, I will close this issue, thanks for your quick reply.
